export const couple = {
  names: "Adrieli & Lucas",
  brideFirstName: "Adrieli",
  groomFirstName: "Lucas",
  date: "21 de novembro de 2026",
  weekDay: "Sábado",
  time: "10h00",
  ceremony: "Paróquia Sagrada Família",
  ceremonyAddress: "R. Manoel Lopes, 1585 - Centro, Lucélia - SP",
  party: "Recanto União",
  partyAddress: "Bairro União - Lucélia - SP",
  ceremonyMapsUrl: "https://maps.app.goo.gl/UGHZVb4AkggGjSRe8",
  partyMapsUrl: "https://maps.app.goo.gl/paaR7vce81LvbKXeA",
  rsvpDeadline: "20 de outubro de 2026",
  welcome:
    "Sejam bem-vindos ao nosso cantinho! Com o coração cheio de alegria, criamos este espaço para compartilhar com vocês cada detalhe de um dos dias mais especiais das nossas vidas. Será uma manhã preparada com muito amor, fé e gratidão, e ter vocês ao nosso lado tornará esse momento ainda mais inesquecível. Obrigada por fazerem parte da nossa história ? estamos contando os dias para celebrar esse sonho com vocês!",
};

export const fallbackGifts = [
  {
    id: "contribuicao-livre",
    name: "Contribuição Livre",
    description: "Escolha o valor que desejar para nos ajudar nesse novo começo.",
    priceCents: null,
    emoji: "+",
    allowCustomAmount: true,
  },
  {
    id: "lua-de-mel",
    name: "Cota Lua de Mel",
    description: "Contribua para a viagem dos nossos sonhos.",
    priceCents: 20000,
    emoji: "LM",
    allowCustomAmount: false,
  },
  {
    id: "casinha-pra-mel",
    name: "Casinha pra Mel",
    description: "Um cantinho especial e confortável para a Mel.",
    priceCents: 30000,
    emoji: "CM",
    allowCustomAmount: false,
  },
  {
    id: "kit-para-churrasco",
    name: "Kit para Churrasco",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 10450,
    emoji: "KP",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-facas",
    name: "Jogo de Facas",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 11115,
    emoji: "JD",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-assadeiras",
    name: "Jogo de Assadeiras",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 22045,
    emoji: "JD",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-panelas",
    name: "Jogo de Panelas",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 22900,
    emoji: "JD",
    allowCustomAmount: false,
  },
  {
    id: "mixer-3-em-1-preto",
    name: "Mixer 3 em 1 Preto",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 20805,
    emoji: "M3",
    allowCustomAmount: false,
  },
  {
    id: "ventilador-de-teto",
    name: "Ventilador de Teto",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 17990,
    emoji: "VD",
    allowCustomAmount: false,
  },
  {
    id: "buffet-aparador-4-portas-mdp-mdf",
    name: "Buffet Aparador 4 Portas MDP/MDF",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 38998,
    emoji: "BA",
    allowCustomAmount: false,
  },
  {
    id: "garrafa-termica1-8-litros",
    name: "Garrafa Térmica1,8 Litros",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 10540,
    emoji: "GT",
    allowCustomAmount: false,
  },
  {
    id: "toalha-de-mesa-retangular-estampado",
    name: "Toalha de Mesa Retangular Estampado",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 10990,
    emoji: "TD",
    allowCustomAmount: false,
  },
  {
    id: "kit-tabua-grande-para-queijos-e-frios-com-petisqueira-quei",
    name: "Kit Tábua Grande Para Queijos E Frios Com Petisqueira Queijo",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 12416,
    emoji: "KT",
    allowCustomAmount: false,
  },
  {
    id: "suqueira-jarra-de-vidro-5-litros-com-torneira",
    name: "Suqueira Jarra De Vidro 5 Litros com Torneira",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 10115,
    emoji: "SJ",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-tacas-em-cristal-6-pecas",
    name: "Jogo de Taças em Cristal 6 Peças",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 13190,
    emoji: "JD",
    allowCustomAmount: false,
  },
  {
    id: "aspirador-de-po-e-agua-1200w",
    name: "Aspirador de Pó e Água 1200W",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 24990,
    emoji: "AD",
    allowCustomAmount: false,
  },
  {
    id: "aspirador-de-po-vertical-2-em-1",
    name: "Aspirador de Pó Vertical 2 em 1",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 14800,
    emoji: "AD",
    allowCustomAmount: false,
  },
  {
    id: "kit-jogo-de-frigideiras-3-pcs-antiaderente",
    name: "Kit Jogo de Frigideiras 3 Pçs Antiaderente",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 11688,
    emoji: "KJ",
    allowCustomAmount: false,
  },
  {
    id: "escorredor-de-louca-rack-preto-2-andares-aco",
    name: "Escorredor de Louça Rack Preto 2 Andares Aço",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 10115,
    emoji: "ED",
    allowCustomAmount: false,
  },
  {
    id: "cortina-100-vedacao-blackout",
    name: "Cortina 100% Vedação Blackout",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 14250,
    emoji: "C1",
    allowCustomAmount: false,
  },
  {
    id: "carrinho-organizador-multiuso-3-andares",
    name: "Carrinho Organizador Multiuso 3 Andares",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 12065,
    emoji: "CO",
    allowCustomAmount: false,
  },
  {
    id: "pipoqueira-pop-time-pip",
    name: "Pipoqueira Pop Time Pip",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 16900,
    emoji: "PP",
    allowCustomAmount: false,
  },
  {
    id: "chaleira-eletrica-com-desligamento-automatico",
    name: "Chaleira Elétrica com Desligamento Automático",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 13940,
    emoji: "CE",
    allowCustomAmount: false,
  },
  {
    id: "geladeira-frost-free-432l-autosense-duplex",
    name: "Geladeira Frost Free 432L AutoSense Duplex",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 294405,
    emoji: "GF",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-lencol-queen-4-pecas-percal-400-fios",
    name: "Jogo de Lençol Queen 4 Peças Percal 400 Fios",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 16990,
    emoji: "JD",
    allowCustomAmount: false,
  },
  {
    id: "edredom-queen-plush-cinza",
    name: "Edredom Queen Plush Cinza",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 24990,
    emoji: "EQ",
    allowCustomAmount: false,
  },
  {
    id: "escada-de-aluminio-5-degraus-residencial",
    name: "Escada de Alumínio 5 degraus Residencial",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 16490,
    emoji: "ED",
    allowCustomAmount: false,
  },
  {
    id: "jogo-toalha-banho-e-rosto-100-algodao",
    name: "Jogo Toalha Banho E Rosto 100% Algodão",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 15510,
    emoji: "JT",
    allowCustomAmount: false,
  },
  {
    id: "kit-2-travesseiros-suporte-extra-firme-branco",
    name: "Kit 2 Travesseiros Suporte Extra Firme Branco",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 15999,
    emoji: "K2",
    allowCustomAmount: false,
  },
  {
    id: "ferro-de-passar-seco-e-vapor",
    name: "Ferro de Passar Seco e Vapor",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 10532,
    emoji: "FD",
    allowCustomAmount: false,
  },
  {
    id: "varal-de-chao-reforcado-c-abas-dobravel-retratil",
    name: "Varal De Chão Reforçado C/abas Dobrável Retrátil",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 10209,
    emoji: "VD",
    allowCustomAmount: false,
  },
  {
    id: "aparelho-de-jantar-e-cha-30-pecas",
    name: "Aparelho De Jantar E Chá 30 Peças",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 34690,
    emoji: "AD",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-jantar-e-cha-20-pecas",
    name: "Jogo De Jantar E Chá 20 Peças",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 23658,
    emoji: "JD",
    allowCustomAmount: false,
  },
  {
    id: "kit-lixeira-em-aco-inox-com-3-pecas",
    name: "Kit Lixeira Em Aço Inox Com 3 Peças",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 19999,
    emoji: "KL",
    allowCustomAmount: false,
  },
  {
    id: "purificador-de-agua-com-compressor-prata",
    name: "Purificador de Água com Compressor Prata",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 109990,
    emoji: "PD",
    allowCustomAmount: false,
  },
  {
    id: "panela-de-pressao-eletrica-6-litros",
    name: "Panela De Pressão Elétrica 6 Litros",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 54990,
    emoji: "PD",
    allowCustomAmount: false,
  },
  {
    id: "batedeira-planetaria-preta",
    name: "Batedeira Planetária Preta",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 49990,
    emoji: "BP",
    allowCustomAmount: false,
  },
  {
    id: "churrasqueira-eletrica-antiaderente",
    name: "Churrasqueira Elétrica Antiaderente",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 24990,
    emoji: "CE",
    allowCustomAmount: false,
  },
  {
    id: "blender-2-jarras-700w",
    name: "Blender 2 Jarras 700w",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 24990,
    emoji: "B2",
    allowCustomAmount: false,
  },
  {
    id: "cervejeira-92-litros-painel-touch",
    name: "Cervejeira 92 Litros Painel Touch",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 199990,
    emoji: "C9",
    allowCustomAmount: false,
  },
  {
    id: "batedeira-duo-mixer-turbo-4-litros",
    name: "Batedeira Duo Mixer Turbo 4 Litros",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 22990,
    emoji: "BD",
    allowCustomAmount: false,
  },
  {
    id: "forno-eletrico-65l",
    name: "Forno Elétrico 65L",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 79990,
    emoji: "FE",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-cama-4-pcs",
    name: "Jogo de Cama 4 pçs",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 9999,
    emoji: "JD",
    allowCustomAmount: false,
  },
  {
    id: "toalha-de-mesa-1-40-x-2-50",
    name: "Toalha de Mesa 1,40 X 2,50",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 9999,
    emoji: "TD",
    allowCustomAmount: false,
  },
  {
    id: "bomboniere-com-pe-cristal-25cm",
    name: "Bomboniere com Pé Cristal 25Cm",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 11999,
    emoji: "BC",
    allowCustomAmount: false,
  },
  {
    id: "bomboniere-com-pe-renaissance-lyor",
    name: "Bomboniere com Pé Renaissance Lyor",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 9999,
    emoji: "BC",
    allowCustomAmount: false,
  },
  {
    id: "prato-de-bolo-com-pe-flor-de-lirio-32cm",
    name: "Prato de Bolo com Pé Flor de Lirio 32Cm",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 9999,
    emoji: "PD",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-potes-hermeticos-10-pecas",
    name: "Jogo de Potes Herméticos 10 Peças",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 12999,
    emoji: "JD",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-travessas-2-pecas",
    name: "Jogo De Travessas 2 Peças",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 19999,
    emoji: "JD",
    allowCustomAmount: false,
  },
  {
    id: "saca-rolhas-eletrico-com-cortador-de-lacre",
    name: "Saca Rolhas Elétrico Com Cortador De Lacre",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 21999,
    emoji: "SR",
    allowCustomAmount: false,
  },
  {
    id: "organizador-para-geladeira-com-3-cestos-5-litros",
    name: "Organizador para Geladeira com 3 Cestos - 5 Litros",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 9999,
    emoji: "OP",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-assadeiras-3-pecas-portuguesa-retangular",
    name: "Jogo de Assadeiras 3 Peças Portuguesa Retangular",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 15999,
    emoji: "JD",
    allowCustomAmount: false,
  },
  {
    id: "boleira-com-tampa-28cm-bambu",
    name: "Boleira com Tampa 28Cm - Bambu",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 9999,
    emoji: "BC",
    allowCustomAmount: false,
  },
  {
    id: "lasanheira-de-vidro-com-tampa-5-litros",
    name: "Lasanheira de Vidro com Tampa 5 Litros",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 9999,
    emoji: "LD",
    allowCustomAmount: false,
  },
  {
    id: "faqueiro-de-inox-60-pecas",
    name: "Faqueiro De Inox - 60 Peças",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 23999,
    emoji: "FD",
    allowCustomAmount: false,
  },
  {
    id: "conjunto-de-facas-com-suporte-7-pecas",
    name: "Conjunto de Facas com Suporte - 7 Peças",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 14999,
    emoji: "CD",
    allowCustomAmount: false,
  },
  {
    id: "tabua-de-churrasco-c-bandeja-e-potes-inox",
    name: "Tábua De Churrasco C/ Bandeja E Potes Inox",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 14999,
    emoji: "TD",
    allowCustomAmount: false,
  },
  {
    id: "panela-eletrica",
    name: "Panela Elétrica",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 19990,
    emoji: "PE",
    allowCustomAmount: false,
  },
  {
    id: "kit-2-poltronas",
    name: "Kit 2 Poltronas",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 69990,
    emoji: "K2",
    allowCustomAmount: false,
  },
  {
    id: "armario-multiuso-4-portas-e-8-prateleiras",
    name: "Armário Multiuso 4 Portas e 8 Prateleiras",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 37998,
    emoji: "AM",
    allowCustomAmount: false,
  },
  {
    id: "cabeceira-casal-com-led-e-2-mesas-de-cabeceira",
    name: "Cabeceira Casal com Led e 2 Mesas de Cabeceira",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 67998,
    emoji: "CC",
    allowCustomAmount: false,
  },
  {
    id: "tapete-para-sala-1-40x2-00-antiderrapante",
    name: "Tapete para Sala 1,40x2,00 Antiderrapante",
    description: "Um presente escolhido com carinho para o nosso novo lar.",
    priceCents: 16119,
    emoji: "TP",
    allowCustomAmount: false,
  },
];

export const giftImageById: Record<string, string> = {
  "contribuicao-livre": "/brand/gifts/contribuicao-livre.jpg",
  "lua-de-mel": "/brand/gifts/lua-de-mel.jpg",
  "casinha-pra-mel": "/brand/gifts/casinha-pra-mel.jpg",
  "kit-para-churrasco": "/brand/gifts/kit-para-churrasco.jpg",
  "jogo-de-facas": "/brand/gifts/jogo-de-facas.jpg",
  "jogo-de-assadeiras": "/brand/gifts/jogo-de-assadeiras.jpg",
  "jogo-de-panelas": "/brand/gifts/jogo-de-panelas.jpg",
  "mixer-3-em-1-preto": "/brand/gifts/mixer-3-em-1-preto.jpg",
  "ventilador-de-teto": "/brand/gifts/ventilador-de-teto.jpg",
  "buffet-aparador-4-portas-mdp-mdf": "/brand/gifts/buffet-aparador-4-portas-mdp-mdf.jpg",
  "garrafa-termica1-8-litros": "/brand/gifts/garrafa-termica1-8-litros.jpg",
  "toalha-de-mesa-retangular-estampado": "/brand/gifts/toalha-de-mesa-retangular-estampado.jpg",
  "kit-tabua-grande-para-queijos-e-frios-com-petisqueira-quei": "/brand/gifts/kit-tabua-grande-para-queijos-e-frios-com-petisqueira-quei.jpg",
  "suqueira-jarra-de-vidro-5-litros-com-torneira": "/brand/gifts/suqueira-jarra-de-vidro-5-litros-com-torneira.jpg",
  "jogo-de-tacas-em-cristal-6-pecas": "/brand/gifts/jogo-de-tacas-em-cristal-6-pecas.jpg",
  "aspirador-de-po-e-agua-1200w": "/brand/gifts/aspirador-de-po-e-agua-1200w.jpg",
  "aspirador-de-po-vertical-2-em-1": "/brand/gifts/aspirador-de-po-vertical-2-em-1.jpg",
  "kit-jogo-de-frigideiras-3-pcs-antiaderente": "/brand/gifts/kit-jogo-de-frigideiras-3-pcs-antiaderente.jpg",
  "escorredor-de-louca-rack-preto-2-andares-aco": "/brand/gifts/escorredor-de-louca-rack-preto-2-andares-aco.jpg",
  "cortina-100-vedacao-blackout": "/brand/gifts/cortina-100-vedacao-blackout.jpg",
  "carrinho-organizador-multiuso-3-andares": "/brand/gifts/carrinho-organizador-multiuso-3-andares.jpg",
  "pipoqueira-pop-time-pip": "/brand/gifts/pipoqueira-pop-time-pip.jpg",
  "chaleira-eletrica-com-desligamento-automatico": "/brand/gifts/chaleira-eletrica-com-desligamento-automatico.jpg",
  "geladeira-frost-free-432l-autosense-duplex": "/brand/gifts/geladeira-frost-free-432l-autosense-duplex.jpg",
  "jogo-de-lencol-queen-4-pecas-percal-400-fios": "/brand/gifts/jogo-de-lencol-queen-4-pecas-percal-400-fios.jpg",
  "edredom-queen-plush-cinza": "/brand/gifts/edredom-queen-plush-cinza.jpg",
  "escada-de-aluminio-5-degraus-residencial": "/brand/gifts/escada-de-aluminio-5-degraus-residencial.jpg",
  "jogo-toalha-banho-e-rosto-100-algodao": "/brand/gifts/jogo-toalha-banho-e-rosto-100-algodao.jpg",
  "kit-2-travesseiros-suporte-extra-firme-branco": "/brand/gifts/kit-2-travesseiros-suporte-extra-firme-branco.jpg",
  "ferro-de-passar-seco-e-vapor": "/brand/gifts/ferro-de-passar-seco-e-vapor.jpg",
  "varal-de-chao-reforcado-c-abas-dobravel-retratil": "/brand/gifts/varal-de-chao-reforcado-c-abas-dobravel-retratil.jpg",
  "aparelho-de-jantar-e-cha-30-pecas": "/brand/gifts/aparelho-de-jantar-e-cha-30-pecas.jpg",
  "jogo-de-jantar-e-cha-20-pecas": "/brand/gifts/jogo-de-jantar-e-cha-20-pecas.jpg",
  "kit-lixeira-em-aco-inox-com-3-pecas": "/brand/gifts/kit-lixeira-em-aco-inox-com-3-pecas.jpg",
  "purificador-de-agua-com-compressor-prata": "/brand/gifts/purificador-de-agua-com-compressor-prata.jpg",
  "panela-de-pressao-eletrica-6-litros": "/brand/gifts/panela-de-pressao-eletrica-6-litros.jpg",
  "batedeira-planetaria-preta": "/brand/gifts/batedeira-planetaria-preta.jpg",
  "churrasqueira-eletrica-antiaderente": "/brand/gifts/churrasqueira-eletrica-antiaderente.jpg",
  "blender-2-jarras-700w": "/brand/gifts/blender-2-jarras-700w.jpg",
  "cervejeira-92-litros-painel-touch": "/brand/gifts/cervejeira-92-litros-painel-touch.jpg",
  "batedeira-duo-mixer-turbo-4-litros": "/brand/gifts/batedeira-duo-mixer-turbo-4-litros.jpg",
  "forno-eletrico-65l": "/brand/gifts/forno-eletrico-65l.jpg",
  "jogo-de-cama-4-pcs": "/brand/gifts/jogo-de-cama-4-pcs.jpg",
  "toalha-de-mesa-1-40-x-2-50": "/brand/gifts/toalha-de-mesa-1-40-x-2-50.jpg",
  "bomboniere-com-pe-cristal-25cm": "/brand/gifts/bomboniere-com-pe-cristal-25cm.jpg",
  "bomboniere-com-pe-renaissance-lyor": "/brand/gifts/bomboniere-com-pe-renaissance-lyor.jpg",
  "prato-de-bolo-com-pe-flor-de-lirio-32cm": "/brand/gifts/prato-de-bolo-com-pe-flor-de-lirio-32cm.jpg",
  "jogo-de-potes-hermeticos-10-pecas": "/brand/gifts/jogo-de-potes-hermeticos-10-pecas.jpg",
  "jogo-de-travessas-2-pecas": "/brand/gifts/jogo-de-travessas-2-pecas.jpg",
  "saca-rolhas-eletrico-com-cortador-de-lacre": "/brand/gifts/saca-rolhas-eletrico-com-cortador-de-lacre.jpg",
  "organizador-para-geladeira-com-3-cestos-5-litros": "/brand/gifts/organizador-para-geladeira-com-3-cestos-5-litros.jpg",
  "jogo-de-assadeiras-3-pecas-portuguesa-retangular": "/brand/gifts/jogo-de-assadeiras-3-pecas-portuguesa-retangular.jpg",
  "boleira-com-tampa-28cm-bambu": "/brand/gifts/boleira-com-tampa-28cm-bambu.jpg",
  "lasanheira-de-vidro-com-tampa-5-litros": "/brand/gifts/lasanheira-de-vidro-com-tampa-5-litros.jpg",
  "faqueiro-de-inox-60-pecas": "/brand/gifts/faqueiro-de-inox-60-pecas.jpg",
  "conjunto-de-facas-com-suporte-7-pecas": "/brand/gifts/conjunto-de-facas-com-suporte-7-pecas.jpg",
  "tabua-de-churrasco-c-bandeja-e-potes-inox": "/brand/gifts/tabua-de-churrasco-c-bandeja-e-potes-inox.jpg",
  "panela-eletrica": "/brand/gifts/panela-eletrica.jpg",
  "kit-2-poltronas": "/brand/gifts/kit-2-poltronas.jpg",
  "armario-multiuso-4-portas-e-8-prateleiras": "/brand/gift-header.jpg",
  "cabeceira-casal-com-led-e-2-mesas-de-cabeceira": "/brand/gifts/cabeceira-casal-com-led-e-2-mesas-de-cabeceira.jpg",
  "tapete-para-sala-1-40x2-00-antiderrapante": "/brand/gifts/tapete-para-sala-1-40x2-00-antiderrapante.jpg",
};

export function formatMoney(cents: number) {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(cents / 100);
}
