export const couple = {
  names: "Adrieli & Lucas",
  brideFirstName: "Adrieli",
  groomFirstName: "Lucas",
  date: "21 de novembro de 2026",
  weekDay: "Sábado",
  time: "10h00",
  ceremony: "Paróquia Sagrada Família",
  ceremonyAddress: "R. Manoel Lopes, 1585 - Centro, Lucélia - SP",
  party: "Recanto União",
  partyAddress: "Bairro União - Lucélia - SP",
  ceremonyMapsUrl: "https://maps.app.goo.gl/UGHZVb4AkggGjSRe8",
  partyMapsUrl: "https://maps.app.goo.gl/paaR7vce81LvbKXeA",
  rsvpDeadline: "20 de outubro de 2026",
  welcome:
    "Sejam bem-vindos ao nosso cantinho! Com o coração cheio de alegria, criamos este espaço para compartilhar com vocês cada detalhe de um dos dias mais especiais das nossas vidas. Será uma manhã preparada com muito amor, fé e gratidão, e ter vocês ao nosso lado tornará esse momento ainda mais inesquecível. Obrigada por fazerem parte da nossa história — estamos contando os dias para celebrar esse sonho com vocês!",
};

export const fallbackGifts = [
  {
    id: "contribuicao-livre",
    name: "Contribuição Livre",
    description: "Escolha o valor que desejar para nos ajudar nesse novo começo.",
    priceCents: null,
    emoji: "+",
    allowCustomAmount: true,
  },
  {
    id: "lua-de-mel",
    name: "Cota Lua de Mel",
    description: "Contribua para a viagem dos nossos sonhos.",
    priceCents: 20000,
    emoji: "LM",
    allowCustomAmount: false,
  },
  {
    id: "geladeira",
    name: "Geladeira",
    description: "Ajude a completar nossa cozinha com esse item essencial.",
    priceCents: 250000,
    emoji: "GE",
    allowCustomAmount: false,
  },
  {
    id: "filtro-de-agua",
    name: "Filtro de Água",
    description: "Para deixar nossa rotina mais prática e saudável.",
    priceCents: 25000,
    emoji: "FA",
    allowCustomAmount: false,
  },
  {
    id: "aspirador-de-po",
    name: "Aspirador de Pó",
    description: "Uma ajuda bem-vinda para manter nosso lar sempre em ordem.",
    priceCents: 35000,
    emoji: "AP",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-cama",
    name: "Jogo de Cama",
    description: "Para deixar nosso quarto mais aconchegante.",
    priceCents: 22000,
    emoji: "JC",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-toalhas",
    name: "Jogo de Toalhas de Banho",
    description: "Um carinho para o enxoval do nosso novo lar.",
    priceCents: 18000,
    emoji: "JT",
    allowCustomAmount: false,
  },
  {
    id: "batedeira",
    name: "Batedeira",
    description: "Para preparar receitas especiais na nossa cozinha.",
    priceCents: 28000,
    emoji: "BT",
    allowCustomAmount: false,
  },
  {
    id: "panela-eletrica",
    name: "Panela Elétrica",
    description: "Mais praticidade para os almoços e jantares a dois.",
    priceCents: 30000,
    emoji: "PE",
    allowCustomAmount: false,
  },
  {
    id: "grill",
    name: "Grill",
    description: "Para refeições rápidas, práticas e gostosas.",
    priceCents: 22000,
    emoji: "GR",
    allowCustomAmount: false,
  },
  {
    id: "chaleira-eletrica",
    name: "Chaleira Elétrica",
    description: "Para café, chá e momentos tranquilos em casa.",
    priceCents: 16000,
    emoji: "CE",
    allowCustomAmount: false,
  },
  {
    id: "casinha-pra-mel",
    name: "Casinha pra Mel",
    description: "Um cantinho especial e confortável para a Mel.",
    priceCents: 30000,
    emoji: "CM",
    allowCustomAmount: false,
  },
  {
    id: "ferro-de-passar",
    name: "Ferro de Passar",
    description: "Um item simples e muito útil para o dia a dia.",
    priceCents: 18000,
    emoji: "FP",
    allowCustomAmount: false,
  },
  {
    id: "aparelho-de-jantar",
    name: "Aparelho de Jantar",
    description: "Para receber com carinho e montar nossa mesa.",
    priceCents: 40000,
    emoji: "AJ",
    allowCustomAmount: false,
  },
  {
    id: "kit-churrasco",
    name: "Kit Churrasco",
    description: "Para preparar momentos especiais com família e amigos.",
    priceCents: 15000,
    emoji: "KC",
    allowCustomAmount: false,
  },
  {
    id: "conjunto-de-facas",
    name: "Conjunto de Facas",
    description: "Um conjunto prático para o dia a dia da nossa cozinha.",
    priceCents: 25000,
    emoji: "CF",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-assadeiras",
    name: "Jogo de Assadeiras",
    description: "Para receitas de forno, almoços e sobremesas especiais.",
    priceCents: 18000,
    emoji: "JA",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-panelas",
    name: "Jogo de Panelas",
    description: "Um presente essencial para completar nossa cozinha.",
    priceCents: 60000,
    emoji: "JP",
    allowCustomAmount: false,
  },
  {
    id: "mixer-com-processador",
    name: "Mixer com Processador",
    description: "Mais praticidade para preparar receitas no dia a dia.",
    priceCents: 30000,
    emoji: "MP",
    allowCustomAmount: false,
  },
  {
    id: "ventilador-de-teto",
    name: "Ventilador de Teto",
    description: "Para deixar nosso lar mais confortável e fresquinho.",
    priceCents: 35000,
    emoji: "VT",
    allowCustomAmount: false,
  },
  {
    id: "aparador",
    name: "Aparador",
    description: "Um móvel lindo e útil para decorar nosso novo lar.",
    priceCents: 70000,
    emoji: "AR",
    allowCustomAmount: false,
  },
  {
    id: "garrafa-termica",
    name: "Garrafa Térmica",
    description: "Para café quentinho e momentos gostosos em casa.",
    priceCents: 12000,
    emoji: "GT",
    allowCustomAmount: false,
  },
  {
    id: "toalha-de-mesa",
    name: "Toalha de Mesa",
    description: "Para montar uma mesa bonita nas nossas refeições.",
    priceCents: 15000,
    emoji: "TM",
    allowCustomAmount: false,
  },
  {
    id: "petisqueira",
    name: "Petisqueira",
    description: "Para servir petiscos e receber pessoas queridas.",
    priceCents: 12000,
    emoji: "PT",
    allowCustomAmount: false,
  },
  {
    id: "suqueira",
    name: "Suqueira",
    description: "Para servir sucos e bebidas com charme.",
    priceCents: 18000,
    emoji: "SQ",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-tacas",
    name: "Jogo de Taças",
    description: "Para brindar momentos especiais da nossa nova vida.",
    priceCents: 22000,
    emoji: "JT",
    allowCustomAmount: false,
  },
  {
    id: "kit-de-frigideiras",
    name: "Kit de Frigideiras",
    description: "Para preparar refeições práticas e deliciosas.",
    priceCents: 30000,
    emoji: "KF",
    allowCustomAmount: false,
  },
];

export function formatMoney(cents: number) {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(cents / 100);
}
