export const couple = {
  names: "Adrieli & Lucas",
  brideFirstName: "Adrieli",
  groomFirstName: "Lucas",
  date: "21 de novembro de 2026",
  weekDay: "Sabado",
  time: "10h00",
  ceremony: "Paroquia Sagrada Familia",
  ceremonyAddress: "R. Manoel Lopes, 1585 - Centro, Lucelia - SP",
  party: "Recanto Uniao",
  partyAddress: "Bairro Uniao - Lucelia - SP",
  ceremonyMapsUrl: "https://maps.app.goo.gl/UGHZVb4AkggGjSRe8",
  partyMapsUrl: "https://maps.app.goo.gl/paaR7vce81LvbKXeA",
  rsvpDeadline: "20 de outubro de 2026",
  welcome:
    "Com o coracao cheio de alegria, convidamos voce para celebrar conosco o inicio da nossa vida a dois. Sera uma manha especial, preparada com amor, fe e gratidao, e a sua presenca tornara esse momento ainda mais inesquecivel.",
};

export const fallbackGifts = [
  {
    id: "contribuicao-livre",
    name: "Contribuicao Livre",
    description: "Escolha o valor que desejar para nos ajudar nesse novo comeco.",
    priceCents: null,
    emoji: "+",
    allowCustomAmount: true,
  },
  {
    id: "lua-de-mel",
    name: "Cota Lua de Mel",
    description: "Contribua para a viagem dos nossos sonhos.",
    priceCents: 20000,
    emoji: "LM",
    allowCustomAmount: false,
  },
  {
    id: "geladeira",
    name: "Geladeira",
    description: "Ajude a completar nossa cozinha com esse item essencial.",
    priceCents: 250000,
    emoji: "GE",
    allowCustomAmount: false,
  },
  {
    id: "filtro-de-agua",
    name: "Filtro de Agua",
    description: "Para deixar nossa rotina mais pratica e saudavel.",
    priceCents: 25000,
    emoji: "FA",
    allowCustomAmount: false,
  },
  {
    id: "aspirador-de-po",
    name: "Aspirador de Po",
    description: "Uma ajuda bem-vinda para manter nosso lar sempre em ordem.",
    priceCents: 35000,
    emoji: "AP",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-cama",
    name: "Jogo de Cama",
    description: "Para deixar nosso quarto mais aconchegante.",
    priceCents: 22000,
    emoji: "JC",
    allowCustomAmount: false,
  },
  {
    id: "jogo-de-toalhas",
    name: "Jogo de Toalhas de Banho",
    description: "Um carinho para o enxoval do nosso novo lar.",
    priceCents: 18000,
    emoji: "JT",
    allowCustomAmount: false,
  },
  {
    id: "batedeira",
    name: "Batedeira",
    description: "Para preparar receitas especiais na nossa cozinha.",
    priceCents: 28000,
    emoji: "BT",
    allowCustomAmount: false,
  },
  {
    id: "panela-eletrica",
    name: "Panela Eletrica",
    description: "Mais praticidade para os almocos e jantares a dois.",
    priceCents: 30000,
    emoji: "PE",
    allowCustomAmount: false,
  },
  {
    id: "grill",
    name: "Grill",
    description: "Para refeicoes rapidas, praticas e gostosas.",
    priceCents: 22000,
    emoji: "GR",
    allowCustomAmount: false,
  },
  {
    id: "chaleira-eletrica",
    name: "Chaleira Eletrica",
    description: "Para cafe, cha e momentos tranquilos em casa.",
    priceCents: 16000,
    emoji: "CE",
    allowCustomAmount: false,
  },
  {
    id: "casinha-pra-mel",
    name: "Casinha pra Mel",
    description: "Um cantinho especial e confortavel para a Mel.",
    priceCents: 30000,
    emoji: "CM",
    allowCustomAmount: false,
  },
  {
    id: "ferro-de-passar",
    name: "Ferro de Passar",
    description: "Um item simples e muito util para o dia a dia.",
    priceCents: 18000,
    emoji: "FP",
    allowCustomAmount: false,
  },
  {
    id: "aparelho-de-jantar",
    name: "Aparelho de Jantar",
    description: "Para receber com carinho e montar nossa mesa.",
    priceCents: 40000,
    emoji: "AJ",
    allowCustomAmount: false,
  },
];

export function formatMoney(cents: number) {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(cents / 100);
}
